Use net-http2 gem for apns auth key client
Promptus/pushmeup pull request #2
Opened 2017-01-20 14:57 UTC by larskuhnt

2017-01-23 17:40 UTC, MGPalmer requested changes

2017-01-23 17:40 UTC, MGPalmer commented on lib/pushmeup/apns/http2_client.rb
>      def close_socket_and_ssl
Is this method even used anymore?

2017-01-23 17:40 UTC, MGPalmer commented on lib/pushmeup/apns/http2_client.rb
> +        @client.join
https://github.com/ostinelli/net-http2

It looks to me as if we're missing the final close of the connection/client, and also shouldn't we "join" outside of the loop?

2017-01-24 08:13 UTC, larskuhnt commented on lib/pushmeup/apns/http2_client.rb
> +        @client.join
the join outside results in errors when sending multiple messages

2017-01-24 08:14 UTC, larskuhnt commented on lib/pushmeup/apns/http2_client.rb
> +        @client.join
if we close it we are not able to reuse the connection, I want the caller to be responsible for closing the connection.

2017-01-24 08:14 UTC, larskuhnt commented on lib/pushmeup/apns/http2_client.rb
>      def close_socket_and_ssl
yes, because the caller is responsible for closing the connection.

2017-01-25 17:35 UTC, MGPalmer approved these changes

2017-01-25 17:35 UTC, merged